// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AvailabilityCalendarUpdate
 */
export interface AvailabilityCalendarUpdate {
    /**
     * @type {string}
     * @memberof AvailabilityCalendarUpdate
     */
    user_id?: string | null;
    /**
     * @type {string}
     * @memberof AvailabilityCalendarUpdate
     */
    start_date?: string | null;
    /**
     * @type {string}
     * @memberof AvailabilityCalendarUpdate
     */
    end_date?: string | null;
    /**
     * @type {string}
     * @memberof AvailabilityCalendarUpdate
     */
    status?: string | null;
    /**
     * @type {string}
     * @memberof AvailabilityCalendarUpdate
     */
    note?: string | null;
}
