// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AvailabilityCalendarResponse,
} from './';

/**
 * @export
 * @interface AvailabilityCalendarListResponse
 */
export interface AvailabilityCalendarListResponse {
    /**
     * @type {number}
     * @memberof AvailabilityCalendarListResponse
     */
    total: number;
    /**
     * @type {number}
     * @memberof AvailabilityCalendarListResponse
     */
    page: number;
    /**
     * @type {number}
     * @memberof AvailabilityCalendarListResponse
     */
    page_size: number;
    /**
     * @type {Array<AvailabilityCalendarResponse>}
     * @memberof AvailabilityCalendarListResponse
     */
    availabilities: Array<AvailabilityCalendarResponse>;
}
