/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvailabilityCalendarResponse } from './AvailabilityCalendarResponse';
import {
    AvailabilityCalendarResponseFromJSON,
    AvailabilityCalendarResponseFromJSONTyped,
    AvailabilityCalendarResponseToJSON,
} from './AvailabilityCalendarResponse';

/**
 * 
 * @export
 * @interface AvailabilityCalendarListResponse
 */
export interface AvailabilityCalendarListResponse {
    /**
     * 
     * @type {number}
     * @memberof AvailabilityCalendarListResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof AvailabilityCalendarListResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof AvailabilityCalendarListResponse
     */
    pageSize: number;
    /**
     * 
     * @type {Array<AvailabilityCalendarResponse>}
     * @memberof AvailabilityCalendarListResponse
     */
    availabilities: Array<AvailabilityCalendarResponse>;
}

/**
 * Check if a given object implements the AvailabilityCalendarListResponse interface.
 */
export function instanceOfAvailabilityCalendarListResponse(value: object): value is AvailabilityCalendarListResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('availabilities' in value) || value['availabilities'] === undefined) return false;
    return true;
}

export function AvailabilityCalendarListResponseFromJSON(json: any): AvailabilityCalendarListResponse {
    return AvailabilityCalendarListResponseFromJSONTyped(json, false);
}

export function AvailabilityCalendarListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailabilityCalendarListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['page_size'],
        'availabilities': ((json['availabilities'] as Array<any>).map(AvailabilityCalendarResponseFromJSON)),
    };
}

export function AvailabilityCalendarListResponseToJSON(value?: AvailabilityCalendarListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'page': value['page'],
        'page_size': value['pageSize'],
        'availabilities': ((value['availabilities'] as Array<any>).map(AvailabilityCalendarResponseToJSON)),
    };
}

