// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    CustomBlockResponse,
} from './';

/**
 * @export
 * @interface CustomBlockListResponse
 */
export interface CustomBlockListResponse {
    /**
     * @type {number}
     * @memberof CustomBlockListResponse
     */
    total: number;
    /**
     * @type {number}
     * @memberof CustomBlockListResponse
     */
    page: number;
    /**
     * @type {number}
     * @memberof CustomBlockListResponse
     */
    page_size: number;
    /**
     * @type {Array<CustomBlockResponse>}
     * @memberof CustomBlockListResponse
     */
    customBlocks: Array<CustomBlockResponse>;
}
