/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomBlockResponse
 */
export interface CustomBlockResponse {
    /**
     * 
     * @type {string}
     * @memberof CustomBlockResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CustomBlockResponse
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CustomBlockResponse
     */
    id: string;
}

/**
 * Check if a given object implements the CustomBlockResponse interface.
 */
export function instanceOfCustomBlockResponse(value: object): value is CustomBlockResponse {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CustomBlockResponseFromJSON(json: any): CustomBlockResponse {
    return CustomBlockResponseFromJSONTyped(json, false);
}

export function CustomBlockResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomBlockResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'id': json['id'],
    };
}

export function CustomBlockResponseToJSON(value?: CustomBlockResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'content': value['content'],
        'id': value['id'],
    };
}

