/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomBlockUpdate
 */
export interface CustomBlockUpdate {
    /**
     * 
     * @type {string}
     * @memberof CustomBlockUpdate
     */
    title: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomBlockUpdate
     */
    content: string | null;
}

/**
 * Check if a given object implements the CustomBlockUpdate interface.
 */
export function instanceOfCustomBlockUpdate(value: object): value is CustomBlockUpdate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CustomBlockUpdateFromJSON(json: any): CustomBlockUpdate {
    return CustomBlockUpdateFromJSONTyped(json, false);
}

export function CustomBlockUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomBlockUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function CustomBlockUpdateToJSON(value?: CustomBlockUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

