/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomBlockCreate
 */
export interface CustomBlockCreate {
    /**
     * 
     * @type {string}
     * @memberof CustomBlockCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CustomBlockCreate
     */
    content: string;
}

/**
 * Check if a given object implements the CustomBlockCreate interface.
 */
export function instanceOfCustomBlockCreate(value: object): value is CustomBlockCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CustomBlockCreateFromJSON(json: any): CustomBlockCreate {
    return CustomBlockCreateFromJSONTyped(json, false);
}

export function CustomBlockCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomBlockCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function CustomBlockCreateToJSON(value?: CustomBlockCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

