// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FeedBackCustomResponse
 */
export interface FeedBackCustomResponse {
    /**
     * @type {string}
     * @memberof FeedBackCustomResponse
     */
    user_id: string;
    /**
     * @type {string}
     * @memberof FeedBackCustomResponse
     */
    project_id: string;
    /**
     * @type {string}
     * @memberof FeedBackCustomResponse
     */
    feedback: string;
    /**
     * @type {number}
     * @memberof FeedBackCustomResponse
     */
    rating: number;
    /**
     * @type {string}
     * @memberof FeedBackCustomResponse
     */
    id: string;
    /**
     * @type {string}
     * @memberof FeedBackCustomResponse
     */
    creation_date: string;
    /**
     * @type {string}
     * @memberof FeedBackCustomResponse
     */
    handler_id: string;
    /**
     * @type {string}
     * @memberof FeedBackCustomResponse
     */
    user_name: string;
    /**
     * @type {string}
     * @memberof FeedBackCustomResponse
     */
    project_name: string;
}
