// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FeedbackUpdate
 */
export interface FeedbackUpdate {
    /**
     * @type {string}
     * @memberof FeedbackUpdate
     */
    user_id?: string | null;
    /**
     * @type {string}
     * @memberof FeedbackUpdate
     */
    project_id?: string | null;
    /**
     * @type {string}
     * @memberof FeedbackUpdate
     */
    feedback?: string | null;
    /**
     * @type {number}
     * @memberof FeedbackUpdate
     */
    rating?: number | null;
}
