/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceInfoCreate
 */
export interface InvoiceInfoCreate {
    /**
     * 
     * @type {string}
     * @memberof InvoiceInfoCreate
     */
    invoiceId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceInfoCreate
     */
    clientName: string;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceInfoCreate
     */
    creationDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceInfoCreate
     */
    expiryDate: Date;
    /**
     * 
     * @type {string}
     * @memberof InvoiceInfoCreate
     */
    clientAddress: string;
    /**
     * 
     * @type {number}
     * @memberof InvoiceInfoCreate
     */
    depositPrice: number;
}

/**
 * Check if a given object implements the InvoiceInfoCreate interface.
 */
export function instanceOfInvoiceInfoCreate(value: object): value is InvoiceInfoCreate {
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    if (!('clientName' in value) || value['clientName'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    if (!('clientAddress' in value) || value['clientAddress'] === undefined) return false;
    if (!('depositPrice' in value) || value['depositPrice'] === undefined) return false;
    return true;
}

export function InvoiceInfoCreateFromJSON(json: any): InvoiceInfoCreate {
    return InvoiceInfoCreateFromJSONTyped(json, false);
}

export function InvoiceInfoCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceInfoCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceId': json['invoice_id'],
        'clientName': json['client_name'],
        'creationDate': (new Date(json['creation_date'])),
        'expiryDate': (new Date(json['expiry_date'])),
        'clientAddress': json['client_address'],
        'depositPrice': json['deposit_price'],
    };
}

export function InvoiceInfoCreateToJSON(value?: InvoiceInfoCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invoice_id': value['invoiceId'],
        'client_name': value['clientName'],
        'creation_date': ((value['creationDate']).toISOString()),
        'expiry_date': ((value['expiryDate']).toISOString()),
        'client_address': value['clientAddress'],
        'deposit_price': value['depositPrice'],
    };
}

