// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InvoiceResponse
 */
export interface InvoiceResponse {
    /**
     * @type {string}
     * @memberof InvoiceResponse
     */
    reference: string;
    /**
     * @type {string}
     * @memberof InvoiceResponse
     */
    user_id: string;
    /**
     * @type {string}
     * @memberof InvoiceResponse
     */
    project_id: string;
    /**
     * @type {string}
     * @memberof InvoiceResponse
     */
    validation_status: string;
    /**
     * @type {string}
     * @memberof InvoiceResponse
     */
    updated_at: string | null;
    /**
     * @type {string}
     * @memberof InvoiceResponse
     */
    id: string;
}
