/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceInfoUpdate
 */
export interface InvoiceInfoUpdate {
    /**
     * 
     * @type {string}
     * @memberof InvoiceInfoUpdate
     */
    clientName: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceInfoUpdate
     */
    creationDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceInfoUpdate
     */
    expiryDate: Date | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceInfoUpdate
     */
    clientAddress: string | null;
    /**
     * 
     * @type {number}
     * @memberof InvoiceInfoUpdate
     */
    depositPrice: number | null;
}

/**
 * Check if a given object implements the InvoiceInfoUpdate interface.
 */
export function instanceOfInvoiceInfoUpdate(value: object): value is InvoiceInfoUpdate {
    if (!('clientName' in value) || value['clientName'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    if (!('clientAddress' in value) || value['clientAddress'] === undefined) return false;
    if (!('depositPrice' in value) || value['depositPrice'] === undefined) return false;
    return true;
}

export function InvoiceInfoUpdateFromJSON(json: any): InvoiceInfoUpdate {
    return InvoiceInfoUpdateFromJSONTyped(json, false);
}

export function InvoiceInfoUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceInfoUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'clientName': json['client_name'],
        'creationDate': (json['creation_date'] == null ? null : new Date(json['creation_date'])),
        'expiryDate': (json['expiry_date'] == null ? null : new Date(json['expiry_date'])),
        'clientAddress': json['client_address'],
        'depositPrice': json['deposit_price'],
    };
}

export function InvoiceInfoUpdateToJSON(value?: InvoiceInfoUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client_name': value['clientName'],
        'creation_date': (value['creationDate'] == null ? null : (value['creationDate'] as any).toISOString()),
        'expiry_date': (value['expiryDate'] == null ? null : (value['expiryDate'] as any).toISOString()),
        'client_address': value['clientAddress'],
        'deposit_price': value['depositPrice'],
    };
}

