// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InvoiceInfoUpdate
 */
export interface InvoiceInfoUpdate {
    /**
     * @type {string}
     * @memberof InvoiceInfoUpdate
     */
    client_name?: string | null;
    /**
     * @type {string}
     * @memberof InvoiceInfoUpdate
     */
    creation_date?: string | null;
    /**
     * @type {string}
     * @memberof InvoiceInfoUpdate
     */
    expiry_date?: string | null;
    /**
     * @type {string}
     * @memberof InvoiceInfoUpdate
     */
    client_address?: string | null;
    /**
     * @type {number}
     * @memberof InvoiceInfoUpdate
     */
    deposit_price?: number | null;
}
