// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InvoiceInfoCreate
 */
export interface InvoiceInfoCreate {
    /**
     * @type {string}
     * @memberof InvoiceInfoCreate
     */
    invoice_id: string;
    /**
     * @type {string}
     * @memberof InvoiceInfoCreate
     */
    client_name: string;
    /**
     * @type {string}
     * @memberof InvoiceInfoCreate
     */
    creation_date: string;
    /**
     * @type {string}
     * @memberof InvoiceInfoCreate
     */
    expiry_date: string;
    /**
     * @type {string}
     * @memberof InvoiceInfoCreate
     */
    client_address: string;
    /**
     * @type {number}
     * @memberof InvoiceInfoCreate
     */
    deposit_price: number;
}
