// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    InvoiceResponse,
} from './';

/**
 * @export
 * @interface InvoiceListResponse
 */
export interface InvoiceListResponse {
    /**
     * @type {number}
     * @memberof InvoiceListResponse
     */
    total: number;
    /**
     * @type {number}
     * @memberof InvoiceListResponse
     */
    page: number;
    /**
     * @type {number}
     * @memberof InvoiceListResponse
     */
    page_size: number;
    /**
     * @type {Array<InvoiceResponse>}
     * @memberof InvoiceListResponse
     */
    invoices: Array<InvoiceResponse>;
}
