// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface MilestoneUpdate
 */
export interface MilestoneUpdate {
    /**
     * @type {string}
     * @memberof MilestoneUpdate
     */
    title?: string | null;
    /**
     * @type {string}
     * @memberof MilestoneUpdate
     */
    description?: string | null;
    /**
     * @type {string}
     * @memberof MilestoneUpdate
     */
    project_id?: string | null;
}
