// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    MilestoneResponse,
} from './';

/**
 * @export
 * @interface MilestoneListResponse
 */
export interface MilestoneListResponse {
    /**
     * @type {number}
     * @memberof MilestoneListResponse
     */
    total: number;
    /**
     * @type {number}
     * @memberof MilestoneListResponse
     */
    page: number;
    /**
     * @type {number}
     * @memberof MilestoneListResponse
     */
    page_size: number;
    /**
     * @type {Array<MilestoneResponse>}
     * @memberof MilestoneListResponse
     */
    milestones: Array<MilestoneResponse>;
}
