// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface MissionCreate
 */
export interface MissionCreate {
    /**
     * @type {string}
     * @memberof MissionCreate
     */
    title: string;
    /**
     * @type {string}
     * @memberof MissionCreate
     */
    description: string;
    /**
     * @type {string}
     * @memberof MissionCreate
     */
    project_id: string;
    /**
     * @type {string}
     * @memberof MissionCreate
     */
    milestone_id: string | null;
    /**
     * @type {string}
     * @memberof MissionCreate
     */
    technology_id: string | null;
    /**
     * @type {string}
     * @memberof MissionCreate
     */
    start_date: string | null;
    /**
     * @type {string}
     * @memberof MissionCreate
     */
    due_date: string | null;
    /**
     * @type {string}
     * @memberof MissionCreate
     */
    estimated_delivery: string | null;
    /**
     * @type {string}
     * @memberof MissionCreate
     */
    status: string;
    /**
     * @type {number}
     * @memberof MissionCreate
     */
    estimated_cost: number | null;
}
