/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionResponse } from './PermissionResponse';
import {
    PermissionResponseFromJSON,
    PermissionResponseFromJSONTyped,
    PermissionResponseToJSON,
} from './PermissionResponse';

/**
 * 
 * @export
 * @interface PermissionListResponse
 */
export interface PermissionListResponse {
    /**
     * 
     * @type {number}
     * @memberof PermissionListResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PermissionListResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PermissionListResponse
     */
    pageSize: number;
    /**
     * 
     * @type {Array<PermissionResponse>}
     * @memberof PermissionListResponse
     */
    permissions: Array<PermissionResponse>;
}

/**
 * Check if a given object implements the PermissionListResponse interface.
 */
export function instanceOfPermissionListResponse(value: object): value is PermissionListResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function PermissionListResponseFromJSON(json: any): PermissionListResponse {
    return PermissionListResponseFromJSONTyped(json, false);
}

export function PermissionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['page_size'],
        'permissions': ((json['permissions'] as Array<any>).map(PermissionResponseFromJSON)),
    };
}

export function PermissionListResponseToJSON(value?: PermissionListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'page': value['page'],
        'page_size': value['pageSize'],
        'permissions': ((value['permissions'] as Array<any>).map(PermissionResponseToJSON)),
    };
}

