/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionResponse
 */
export interface PermissionResponse {
    /**
     * 
     * @type {string}
     * @memberof PermissionResponse
     */
    roleId: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof PermissionResponse
     */
    creationDate: Date;
}

/**
 * Check if a given object implements the PermissionResponse interface.
 */
export function instanceOfPermissionResponse(value: object): value is PermissionResponse {
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    return true;
}

export function PermissionResponseFromJSON(json: any): PermissionResponse {
    return PermissionResponseFromJSONTyped(json, false);
}

export function PermissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'roleId': json['role_id'],
        'name': json['name'],
        'description': json['description'],
        'id': json['id'],
        'creationDate': (new Date(json['creation_date'])),
    };
}

export function PermissionResponseToJSON(value?: PermissionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role_id': value['roleId'],
        'name': value['name'],
        'description': value['description'],
        'id': value['id'],
        'creation_date': ((value['creationDate']).toISOString()),
    };
}

