/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionCreate
 */
export interface PermissionCreate {
    /**
     * 
     * @type {string}
     * @memberof PermissionCreate
     */
    roleId: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionCreate
     */
    description: string;
}

/**
 * Check if a given object implements the PermissionCreate interface.
 */
export function instanceOfPermissionCreate(value: object): value is PermissionCreate {
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PermissionCreateFromJSON(json: any): PermissionCreate {
    return PermissionCreateFromJSONTyped(json, false);
}

export function PermissionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'roleId': json['role_id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function PermissionCreateToJSON(value?: PermissionCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role_id': value['roleId'],
        'name': value['name'],
        'description': value['description'],
    };
}

