// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    PricingResponse,
} from './';

/**
 * @export
 * @interface PricingListResponse
 */
export interface PricingListResponse {
    /**
     * @type {number}
     * @memberof PricingListResponse
     */
    total: number;
    /**
     * @type {number}
     * @memberof PricingListResponse
     */
    page: number;
    /**
     * @type {number}
     * @memberof PricingListResponse
     */
    page_size: number;
    /**
     * @type {Array<PricingResponse>}
     * @memberof PricingListResponse
     */
    pricing: Array<PricingResponse>;
}
