// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ProjectStatusEnum,
} from './';

/**
 * @export
 * @interface ProjectUpdate
 */
export interface ProjectUpdate {
    /**
     * @type {string}
     * @memberof ProjectUpdate
     */
    title?: string | null;
    /**
     * @type {string}
     * @memberof ProjectUpdate
     */
    description?: string | null;
    /**
     * @type {ProjectStatusEnum}
     * @memberof ProjectUpdate
     */
    status?: ProjectStatusEnum | null;
    /**
     * @type {string}
     * @memberof ProjectUpdate
     */
    start_date?: string | null;
    /**
     * @type {string}
     * @memberof ProjectUpdate
     */
    end_date?: string | null;
    /**
     * @type {number}
     * @memberof ProjectUpdate
     */
    total_price?: number | null;
    /**
     * @type {string}
     * @memberof ProjectUpdate
     */
    client_id?: string | null;
    /**
     * @type {string}
     * @memberof ProjectUpdate
     */
    handler_id?: string | null;
    /**
     * @type {number}
     * @memberof ProjectUpdate
     */
    tax_rate?: number | null;
}


