// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ProjectStatusEnum,
} from './';

/**
 * @export
 * @interface ProjectCreate
 */
export interface ProjectCreate {
    /**
     * @type {string}
     * @memberof ProjectCreate
     */
    title: string;
    /**
     * @type {string}
     * @memberof ProjectCreate
     */
    description: string;
    /**
     * @type {ProjectStatusEnum}
     * @memberof ProjectCreate
     */
    status: ProjectStatusEnum;
    /**
     * @type {string}
     * @memberof ProjectCreate
     */
    start_date: string | null;
    /**
     * @type {string}
     * @memberof ProjectCreate
     */
    end_date: string | null;
    /**
     * @type {number}
     * @memberof ProjectCreate
     */
    total_price: number | null;
    /**
     * @type {number}
     * @memberof ProjectCreate
     */
    tax_rate: number | null;
    /**
     * @type {string}
     * @memberof ProjectCreate
     */
    client_id: string;
}


