/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectResponse
     */
    startDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectResponse
     */
    endDate: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectResponse
     */
    totalPrice: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectResponse
     */
    taxRate: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectResponse
     */
    creationDate: Date;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    clientId: string;
}

/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): value is ProjectResponse {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
    if (!('taxRate' in value) || value['taxRate'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    return true;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
    return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'status': json['status'],
        'startDate': (json['start_date'] == null ? null : new Date(json['start_date'])),
        'endDate': (json['end_date'] == null ? null : new Date(json['end_date'])),
        'totalPrice': json['total_price'],
        'taxRate': json['tax_rate'],
        'id': json['id'],
        'creationDate': (new Date(json['creation_date'])),
        'clientId': json['client_id'],
    };
}

export function ProjectResponseToJSON(value?: ProjectResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
        'start_date': (value['startDate'] == null ? null : (value['startDate'] as any).toISOString().substring(0,10)),
        'end_date': (value['endDate'] == null ? null : (value['endDate'] as any).toISOString().substring(0,10)),
        'total_price': value['totalPrice'],
        'tax_rate': value['taxRate'],
        'id': value['id'],
        'creation_date': ((value['creationDate']).toISOString()),
        'client_id': value['clientId'],
    };
}

