/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleCreate
 */
export interface RoleCreate {
    /**
     * 
     * @type {string}
     * @memberof RoleCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoleCreate
     */
    description: string;
}

/**
 * Check if a given object implements the RoleCreate interface.
 */
export function instanceOfRoleCreate(value: object): value is RoleCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function RoleCreateFromJSON(json: any): RoleCreate {
    return RoleCreateFromJSONTyped(json, false);
}

export function RoleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function RoleCreateToJSON(value?: RoleCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

