/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagCreate
 */
export interface TagCreate {
    /**
     * 
     * @type {string}
     * @memberof TagCreate
     */
    name: string;
}

/**
 * Check if a given object implements the TagCreate interface.
 */
export function instanceOfTagCreate(value: object): value is TagCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TagCreateFromJSON(json: any): TagCreate {
    return TagCreateFromJSONTyped(json, false);
}

export function TagCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TagCreateToJSON(value?: TagCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

