// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    TagResponse,
} from './';

/**
 * @export
 * @interface TagListResponse
 */
export interface TagListResponse {
    /**
     * @type {number}
     * @memberof TagListResponse
     */
    total: number;
    /**
     * @type {number}
     * @memberof TagListResponse
     */
    page: number;
    /**
     * @type {number}
     * @memberof TagListResponse
     */
    page_size: number;
    /**
     * @type {Array<TagResponse>}
     * @memberof TagListResponse
     */
    tags: Array<TagResponse>;
}
