// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    TechnologyResponse,
} from './';

/**
 * @export
 * @interface TechnologyListResponse
 */
export interface TechnologyListResponse {
    /**
     * @type {number}
     * @memberof TechnologyListResponse
     */
    total: number;
    /**
     * @type {number}
     * @memberof TechnologyListResponse
     */
    page: number;
    /**
     * @type {number}
     * @memberof TechnologyListResponse
     */
    page_size: number;
    /**
     * @type {Array<TechnologyResponse>}
     * @memberof TechnologyListResponse
     */
    technologies: Array<TechnologyResponse>;
}
