/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TechnologyUpdate
 */
export interface TechnologyUpdate {
    /**
     * 
     * @type {string}
     * @memberof TechnologyUpdate
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof TechnologyUpdate
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof TechnologyUpdate
     */
    tagId: string | null;
    /**
     * 
     * @type {string}
     * @memberof TechnologyUpdate
     */
    language: string | null;
}

/**
 * Check if a given object implements the TechnologyUpdate interface.
 */
export function instanceOfTechnologyUpdate(value: object): value is TechnologyUpdate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    return true;
}

export function TechnologyUpdateFromJSON(json: any): TechnologyUpdate {
    return TechnologyUpdateFromJSONTyped(json, false);
}

export function TechnologyUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnologyUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'tagId': json['tag_id'],
        'language': json['language'],
    };
}

export function TechnologyUpdateToJSON(value?: TechnologyUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'tag_id': value['tagId'],
        'language': value['language'],
    };
}

