// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TechnologyCreate
 */
export interface TechnologyCreate {
    /**
     * @type {string}
     * @memberof TechnologyCreate
     */
    name: string;
    /**
     * @type {string}
     * @memberof TechnologyCreate
     */
    description: string;
    /**
     * @type {string}
     * @memberof TechnologyCreate
     */
    tag_id: string;
    /**
     * @type {string}
     * @memberof TechnologyCreate
     */
    language: string;
}
