// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TechnologyResponse
 */
export interface TechnologyResponse {
    /**
     * @type {string}
     * @memberof TechnologyResponse
     */
    name: string;
    /**
     * @type {string}
     * @memberof TechnologyResponse
     */
    description: string;
    /**
     * @type {string}
     * @memberof TechnologyResponse
     */
    tag_id: string;
    /**
     * @type {string}
     * @memberof TechnologyResponse
     */
    language: string;
    /**
     * @type {string}
     * @memberof TechnologyResponse
     */
    id: string;
    /**
     * @type {string}
     * @memberof TechnologyResponse
     */
    creation_date: string;
}
