// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UserUpdate
 */
export interface UserUpdate {
    /**
     * @type {string}
     * @memberof UserUpdate
     */
    name?: string | null;
    /**
     * @type {string}
     * @memberof UserUpdate
     */
    description?: string | null;
    /**
     * @type {string}
     * @memberof UserUpdate
     */
    email?: string | null;
    /**
     * @type {string}
     * @memberof UserUpdate
     */
    password?: string | null;
    /**
     * @type {boolean}
     * @memberof UserUpdate
     */
    active?: boolean | null;
}
