// tslint:disable
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    CustomBlockListResponse,
    HTTPValidationError,
    InvoiceHasCustomBlockCreate,
    InvoiceListResponse,
} from '../models';

export interface CreateApiInvoicesBlocksPostRequest {
    invoiceHasCustomBlockCreate: InvoiceHasCustomBlockCreate;
}

export interface DeleteApiInvoicesBlocksInvoiceIdCustomBlockIdDeleteRequest {
    invoiceId: string;
    customBlockId: string;
}

export interface GetCustomBlocksApiInvoicesBlocksInvoicesInvoiceIdCustomBlocksGetRequest {
    invoiceId: string;
}

export interface GetInvoicesApiInvoicesBlocksCustomBlocksCustomBlockIdInvoicesGetRequest {
    customBlockId: string;
}

/**
 * no description
 */
export class InvoicesBlocksApi extends BaseAPI {

    /**
     * Create an association between an invoice and a custom block.
     * Create
     */
    createApiInvoicesBlocksPost({ invoiceHasCustomBlockCreate }: CreateApiInvoicesBlocksPostRequest): Observable<any>
    createApiInvoicesBlocksPost({ invoiceHasCustomBlockCreate }: CreateApiInvoicesBlocksPostRequest, opts?: OperationOpts): Observable<AjaxResponse<any>>
    createApiInvoicesBlocksPost({ invoiceHasCustomBlockCreate }: CreateApiInvoicesBlocksPostRequest, opts?: OperationOpts): Observable<any | AjaxResponse<any>> {
        throwIfNullOrUndefined(invoiceHasCustomBlockCreate, 'invoiceHasCustomBlockCreate', 'createApiInvoicesBlocksPost');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<any>({
            url: '/api/invoices_blocks/',
            method: 'POST',
            headers,
            body: invoiceHasCustomBlockCreate,
        }, opts?.responseOpts);
    };

    /**
     * Delete an association between an invoice and a custom block.
     * Delete
     */
    deleteApiInvoicesBlocksInvoiceIdCustomBlockIdDelete({ invoiceId, customBlockId }: DeleteApiInvoicesBlocksInvoiceIdCustomBlockIdDeleteRequest): Observable<any>
    deleteApiInvoicesBlocksInvoiceIdCustomBlockIdDelete({ invoiceId, customBlockId }: DeleteApiInvoicesBlocksInvoiceIdCustomBlockIdDeleteRequest, opts?: OperationOpts): Observable<AjaxResponse<any>>
    deleteApiInvoicesBlocksInvoiceIdCustomBlockIdDelete({ invoiceId, customBlockId }: DeleteApiInvoicesBlocksInvoiceIdCustomBlockIdDeleteRequest, opts?: OperationOpts): Observable<any | AjaxResponse<any>> {
        throwIfNullOrUndefined(invoiceId, 'invoiceId', 'deleteApiInvoicesBlocksInvoiceIdCustomBlockIdDelete');
        throwIfNullOrUndefined(customBlockId, 'customBlockId', 'deleteApiInvoicesBlocksInvoiceIdCustomBlockIdDelete');

        return this.request<any>({
            url: '/api/invoices_blocks/{invoice_id}/{custom_block_id}'.replace('{invoice_id}', encodeURI(invoiceId)).replace('{custom_block_id}', encodeURI(customBlockId)),
            method: 'DELETE',
        }, opts?.responseOpts);
    };

    /**
     * Retrieve all custom blocks associated with a specific invoice.
     * Get Custom Blocks
     */
    getCustomBlocksApiInvoicesBlocksInvoicesInvoiceIdCustomBlocksGet({ invoiceId }: GetCustomBlocksApiInvoicesBlocksInvoicesInvoiceIdCustomBlocksGetRequest): Observable<CustomBlockListResponse>
    getCustomBlocksApiInvoicesBlocksInvoicesInvoiceIdCustomBlocksGet({ invoiceId }: GetCustomBlocksApiInvoicesBlocksInvoicesInvoiceIdCustomBlocksGetRequest, opts?: OperationOpts): Observable<AjaxResponse<CustomBlockListResponse>>
    getCustomBlocksApiInvoicesBlocksInvoicesInvoiceIdCustomBlocksGet({ invoiceId }: GetCustomBlocksApiInvoicesBlocksInvoicesInvoiceIdCustomBlocksGetRequest, opts?: OperationOpts): Observable<CustomBlockListResponse | AjaxResponse<CustomBlockListResponse>> {
        throwIfNullOrUndefined(invoiceId, 'invoiceId', 'getCustomBlocksApiInvoicesBlocksInvoicesInvoiceIdCustomBlocksGet');

        return this.request<CustomBlockListResponse>({
            url: '/api/invoices_blocks/invoices/{invoice_id}/custom_blocks'.replace('{invoice_id}', encodeURI(invoiceId)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Retrieve all invoices associated with a specific custom block.
     * Get Invoices
     */
    getInvoicesApiInvoicesBlocksCustomBlocksCustomBlockIdInvoicesGet({ customBlockId }: GetInvoicesApiInvoicesBlocksCustomBlocksCustomBlockIdInvoicesGetRequest): Observable<InvoiceListResponse>
    getInvoicesApiInvoicesBlocksCustomBlocksCustomBlockIdInvoicesGet({ customBlockId }: GetInvoicesApiInvoicesBlocksCustomBlocksCustomBlockIdInvoicesGetRequest, opts?: OperationOpts): Observable<AjaxResponse<InvoiceListResponse>>
    getInvoicesApiInvoicesBlocksCustomBlocksCustomBlockIdInvoicesGet({ customBlockId }: GetInvoicesApiInvoicesBlocksCustomBlocksCustomBlockIdInvoicesGetRequest, opts?: OperationOpts): Observable<InvoiceListResponse | AjaxResponse<InvoiceListResponse>> {
        throwIfNullOrUndefined(customBlockId, 'customBlockId', 'getInvoicesApiInvoicesBlocksCustomBlocksCustomBlockIdInvoicesGet');

        return this.request<InvoiceListResponse>({
            url: '/api/invoices_blocks/custom_blocks/{custom_block_id}/invoices'.replace('{custom_block_id}', encodeURI(customBlockId)),
            method: 'GET',
        }, opts?.responseOpts);
    };

}
