/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomBlockResponse } from './CustomBlockResponse';
import {
    CustomBlockResponseFromJSON,
    CustomBlockResponseFromJSONTyped,
    CustomBlockResponseToJSON,
} from './CustomBlockResponse';

/**
 * 
 * @export
 * @interface CustomBlockListResponse
 */
export interface CustomBlockListResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomBlockListResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof CustomBlockListResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CustomBlockListResponse
     */
    pageSize: number;
    /**
     * 
     * @type {Array<CustomBlockResponse>}
     * @memberof CustomBlockListResponse
     */
    customBlocks: Array<CustomBlockResponse>;
}

/**
 * Check if a given object implements the CustomBlockListResponse interface.
 */
export function instanceOfCustomBlockListResponse(value: object): value is CustomBlockListResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('customBlocks' in value) || value['customBlocks'] === undefined) return false;
    return true;
}

export function CustomBlockListResponseFromJSON(json: any): CustomBlockListResponse {
    return CustomBlockListResponseFromJSONTyped(json, false);
}

export function CustomBlockListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomBlockListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['page_size'],
        'customBlocks': ((json['customBlocks'] as Array<any>).map(CustomBlockResponseFromJSON)),
    };
}

export function CustomBlockListResponseToJSON(value?: CustomBlockListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'page': value['page'],
        'page_size': value['pageSize'],
        'customBlocks': ((value['customBlocks'] as Array<any>).map(CustomBlockResponseToJSON)),
    };
}

