/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackResponse
 */
export interface FeedbackResponse {
    /**
     * 
     * @type {string}
     * @memberof FeedbackResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackResponse
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackResponse
     */
    feedback: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackResponse
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof FeedbackResponse
     */
    creationDate: Date;
}

/**
 * Check if a given object implements the FeedbackResponse interface.
 */
export function instanceOfFeedbackResponse(value: object): value is FeedbackResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('feedback' in value) || value['feedback'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    return true;
}

export function FeedbackResponseFromJSON(json: any): FeedbackResponse {
    return FeedbackResponseFromJSONTyped(json, false);
}

export function FeedbackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'projectId': json['project_id'],
        'feedback': json['feedback'],
        'rating': json['rating'],
        'id': json['id'],
        'creationDate': (new Date(json['creation_date'])),
    };
}

export function FeedbackResponseToJSON(value?: FeedbackResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_id': value['userId'],
        'project_id': value['projectId'],
        'feedback': value['feedback'],
        'rating': value['rating'],
        'id': value['id'],
        'creation_date': ((value['creationDate']).toISOString()),
    };
}

