/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackUpdate
 */
export interface FeedbackUpdate {
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdate
     */
    userId: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdate
     */
    projectId: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdate
     */
    feedback: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackUpdate
     */
    rating: number | null;
}

/**
 * Check if a given object implements the FeedbackUpdate interface.
 */
export function instanceOfFeedbackUpdate(value: object): value is FeedbackUpdate {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('feedback' in value) || value['feedback'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function FeedbackUpdateFromJSON(json: any): FeedbackUpdate {
    return FeedbackUpdateFromJSONTyped(json, false);
}

export function FeedbackUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'projectId': json['project_id'],
        'feedback': json['feedback'],
        'rating': json['rating'],
    };
}

export function FeedbackUpdateToJSON(value?: FeedbackUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_id': value['userId'],
        'project_id': value['projectId'],
        'feedback': value['feedback'],
        'rating': value['rating'],
    };
}

