/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackCreate
 */
export interface FeedbackCreate {
    /**
     * 
     * @type {string}
     * @memberof FeedbackCreate
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackCreate
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackCreate
     */
    feedback: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackCreate
     */
    rating: number;
}

/**
 * Check if a given object implements the FeedbackCreate interface.
 */
export function instanceOfFeedbackCreate(value: object): value is FeedbackCreate {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('feedback' in value) || value['feedback'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function FeedbackCreateFromJSON(json: any): FeedbackCreate {
    return FeedbackCreateFromJSONTyped(json, false);
}

export function FeedbackCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'projectId': json['project_id'],
        'feedback': json['feedback'],
        'rating': json['rating'],
    };
}

export function FeedbackCreateToJSON(value?: FeedbackCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_id': value['userId'],
        'project_id': value['projectId'],
        'feedback': value['feedback'],
        'rating': value['rating'],
    };
}

