/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceHasCustomBlockCreate
 */
export interface InvoiceHasCustomBlockCreate {
    /**
     * 
     * @type {string}
     * @memberof InvoiceHasCustomBlockCreate
     */
    invoiceId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceHasCustomBlockCreate
     */
    customBlockId: string;
}

/**
 * Check if a given object implements the InvoiceHasCustomBlockCreate interface.
 */
export function instanceOfInvoiceHasCustomBlockCreate(value: object): value is InvoiceHasCustomBlockCreate {
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    if (!('customBlockId' in value) || value['customBlockId'] === undefined) return false;
    return true;
}

export function InvoiceHasCustomBlockCreateFromJSON(json: any): InvoiceHasCustomBlockCreate {
    return InvoiceHasCustomBlockCreateFromJSONTyped(json, false);
}

export function InvoiceHasCustomBlockCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceHasCustomBlockCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceId': json['invoice_id'],
        'customBlockId': json['custom_block_id'],
    };
}

export function InvoiceHasCustomBlockCreateToJSON(value?: InvoiceHasCustomBlockCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invoice_id': value['invoiceId'],
        'custom_block_id': value['customBlockId'],
    };
}

