/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MilestoneCreate
 */
export interface MilestoneCreate {
    /**
     * 
     * @type {string}
     * @memberof MilestoneCreate
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneCreate
     */
    description: string;
}

/**
 * Check if a given object implements the MilestoneCreate interface.
 */
export function instanceOfMilestoneCreate(value: object): value is MilestoneCreate {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function MilestoneCreateFromJSON(json: any): MilestoneCreate {
    return MilestoneCreateFromJSONTyped(json, false);
}

export function MilestoneCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MilestoneCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'title': json['title'],
        'description': json['description'],
    };
}

export function MilestoneCreateToJSON(value?: MilestoneCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'project_id': value['projectId'],
        'title': value['title'],
        'description': value['description'],
    };
}

