/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MilestoneResponse
 */
export interface MilestoneResponse {
    /**
     * 
     * @type {string}
     * @memberof MilestoneResponse
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof MilestoneResponse
     */
    creationDate: Date;
}

/**
 * Check if a given object implements the MilestoneResponse interface.
 */
export function instanceOfMilestoneResponse(value: object): value is MilestoneResponse {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    return true;
}

export function MilestoneResponseFromJSON(json: any): MilestoneResponse {
    return MilestoneResponseFromJSONTyped(json, false);
}

export function MilestoneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MilestoneResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'title': json['title'],
        'description': json['description'],
        'id': json['id'],
        'creationDate': (new Date(json['creation_date'])),
    };
}

export function MilestoneResponseToJSON(value?: MilestoneResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'project_id': value['projectId'],
        'title': value['title'],
        'description': value['description'],
        'id': value['id'],
        'creation_date': ((value['creationDate']).toISOString()),
    };
}

