/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionUpdate
 */
export interface PermissionUpdate {
    /**
     * 
     * @type {string}
     * @memberof PermissionUpdate
     */
    roleId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PermissionUpdate
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof PermissionUpdate
     */
    description: string | null;
}

/**
 * Check if a given object implements the PermissionUpdate interface.
 */
export function instanceOfPermissionUpdate(value: object): value is PermissionUpdate {
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PermissionUpdateFromJSON(json: any): PermissionUpdate {
    return PermissionUpdateFromJSONTyped(json, false);
}

export function PermissionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'roleId': json['role_id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function PermissionUpdateToJSON(value?: PermissionUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role_id': value['roleId'],
        'name': value['name'],
        'description': value['description'],
    };
}

