/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PricingUpdate
 */
export interface PricingUpdate {
    /**
     * 
     * @type {string}
     * @memberof PricingUpdate
     */
    tagId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PricingUpdate
     */
    userId: string | null;
    /**
     * 
     * @type {number}
     * @memberof PricingUpdate
     */
    pricePerDay: number | null;
}

/**
 * Check if a given object implements the PricingUpdate interface.
 */
export function instanceOfPricingUpdate(value: object): value is PricingUpdate {
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('pricePerDay' in value) || value['pricePerDay'] === undefined) return false;
    return true;
}

export function PricingUpdateFromJSON(json: any): PricingUpdate {
    return PricingUpdateFromJSONTyped(json, false);
}

export function PricingUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'tagId': json['tag_id'],
        'userId': json['user_id'],
        'pricePerDay': json['price_per_day'],
    };
}

export function PricingUpdateToJSON(value?: PricingUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tag_id': value['tagId'],
        'user_id': value['userId'],
        'price_per_day': value['pricePerDay'],
    };
}

