/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PricingCreate
 */
export interface PricingCreate {
    /**
     * 
     * @type {string}
     * @memberof PricingCreate
     */
    tagId: string;
    /**
     * 
     * @type {string}
     * @memberof PricingCreate
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof PricingCreate
     */
    pricePerDay: number;
}

/**
 * Check if a given object implements the PricingCreate interface.
 */
export function instanceOfPricingCreate(value: object): value is PricingCreate {
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('pricePerDay' in value) || value['pricePerDay'] === undefined) return false;
    return true;
}

export function PricingCreateFromJSON(json: any): PricingCreate {
    return PricingCreateFromJSONTyped(json, false);
}

export function PricingCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'tagId': json['tag_id'],
        'userId': json['user_id'],
        'pricePerDay': json['price_per_day'],
    };
}

export function PricingCreateToJSON(value?: PricingCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tag_id': value['tagId'],
        'user_id': value['userId'],
        'price_per_day': value['pricePerDay'],
    };
}

