/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectCreate
 */
export interface ProjectCreate {
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectCreate
     */
    startDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectCreate
     */
    endDate: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectCreate
     */
    totalPrice: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectCreate
     */
    taxRate: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    clientId: string;
}

/**
 * Check if a given object implements the ProjectCreate interface.
 */
export function instanceOfProjectCreate(value: object): value is ProjectCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
    if (!('taxRate' in value) || value['taxRate'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    return true;
}

export function ProjectCreateFromJSON(json: any): ProjectCreate {
    return ProjectCreateFromJSONTyped(json, false);
}

export function ProjectCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'status': json['status'],
        'startDate': (json['start_date'] == null ? null : new Date(json['start_date'])),
        'endDate': (json['end_date'] == null ? null : new Date(json['end_date'])),
        'totalPrice': json['total_price'],
        'taxRate': json['tax_rate'],
        'clientId': json['client_id'],
    };
}

export function ProjectCreateToJSON(value?: ProjectCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
        'start_date': (value['startDate'] == null ? null : (value['startDate'] as any).toISOString().substring(0,10)),
        'end_date': (value['endDate'] == null ? null : (value['endDate'] as any).toISOString().substring(0,10)),
        'total_price': value['totalPrice'],
        'tax_rate': value['taxRate'],
        'client_id': value['clientId'],
    };
}

