/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TechnologyResponse
 */
export interface TechnologyResponse {
    /**
     * 
     * @type {string}
     * @memberof TechnologyResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TechnologyResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof TechnologyResponse
     */
    tagId: string;
    /**
     * 
     * @type {string}
     * @memberof TechnologyResponse
     */
    language: string;
    /**
     * 
     * @type {string}
     * @memberof TechnologyResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TechnologyResponse
     */
    creationDate: Date;
}

/**
 * Check if a given object implements the TechnologyResponse interface.
 */
export function instanceOfTechnologyResponse(value: object): value is TechnologyResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    return true;
}

export function TechnologyResponseFromJSON(json: any): TechnologyResponse {
    return TechnologyResponseFromJSONTyped(json, false);
}

export function TechnologyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnologyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'tagId': json['tag_id'],
        'language': json['language'],
        'id': json['id'],
        'creationDate': (new Date(json['creation_date'])),
    };
}

export function TechnologyResponseToJSON(value?: TechnologyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'tag_id': value['tagId'],
        'language': value['language'],
        'id': value['id'],
        'creation_date': ((value['creationDate']).toISOString()),
    };
}

