/* tslint:disable */
/* eslint-disable */
/**
 * Project Manager ( Portfolio )
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TechnologyResponse } from './TechnologyResponse';
import {
    TechnologyResponseFromJSON,
    TechnologyResponseFromJSONTyped,
    TechnologyResponseToJSON,
} from './TechnologyResponse';

/**
 * 
 * @export
 * @interface TechnologyListResponse
 */
export interface TechnologyListResponse {
    /**
     * 
     * @type {number}
     * @memberof TechnologyListResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof TechnologyListResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof TechnologyListResponse
     */
    pageSize: number;
    /**
     * 
     * @type {Array<TechnologyResponse>}
     * @memberof TechnologyListResponse
     */
    technologies: Array<TechnologyResponse>;
}

/**
 * Check if a given object implements the TechnologyListResponse interface.
 */
export function instanceOfTechnologyListResponse(value: object): value is TechnologyListResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('technologies' in value) || value['technologies'] === undefined) return false;
    return true;
}

export function TechnologyListResponseFromJSON(json: any): TechnologyListResponse {
    return TechnologyListResponseFromJSONTyped(json, false);
}

export function TechnologyListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnologyListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['page_size'],
        'technologies': ((json['technologies'] as Array<any>).map(TechnologyResponseFromJSON)),
    };
}

export function TechnologyListResponseToJSON(value?: TechnologyListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'page': value['page'],
        'page_size': value['pageSize'],
        'technologies': ((value['technologies'] as Array<any>).map(TechnologyResponseToJSON)),
    };
}

