// tslint:disable
/**
 * Secure CDN API
 * API for managing a secure CDN with JWT authentication
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LoginPost200Response
 */
export interface LoginPost200Response {
    /**
     * @type {string}
     * @memberof LoginPost200Response
     */
    token?: string;
}
