// tslint:disable
/**
 * Secure CDN API
 * API pour la gestion d\'un CDN sécurisé avec authentification JWT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RegisterPostRequest
 */
export interface RegisterPostRequest {
    /**
     * @type {string}
     * @memberof RegisterPostRequest
     */
    userId: string;
    /**
     * @type {string}
     * @memberof RegisterPostRequest
     */
    password: string;
}
